"""Auto-generated enums from ontology definitions.

This file is automatically generated by scripts/generate_enums.py.
Do not edit manually - run the script to regenerate.
"""

from enum import Enum

class NodeTypeEnum(str, Enum):
    """Enumeration of node types in the knowledge graph."""
    Event = "Event"
    Floor = "Floor"
    Interest = "Interest"
    Message = "Message"
    Project = "Project"
    Task = "Task"
    Topic = "Topic"
    User = "User"

class EdgeTypeEnum(str, Enum):
    """Enumeration of edge types in the knowledge graph."""
    AssignedTo = "ASSIGNED_TO"
    Attends = "ATTENDS"
    InterestedIn = "INTERESTED_IN"
    InReplyTo = "IN_REPLY_TO"
    LocatedOn = "LOCATED_ON"
    RelatedTo = "RELATED_TO"
    Sent = "SENT"
    SentIn = "SENT_IN"
    WorksOn = "WORKS_ON"
